modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3.0-only"

[[mods]]
modId = "iris"
version = "${version}"
displayName = "Iris Shaders - Unofficial 92d421c BackPort"

logoFile = "iris-logo.png" #optional

authors = "lsybek (Original by coderbot, IMS212)"

description = '''
An unofficial backport of commit 92d421c for Iris Shaders.
Fixes particle rendering/blur issues in Minecraft 1.21.1.

Original mod by coderbot and IMS212.
'''

[[dependencies.iris]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "mixins.iris.json"

[[mixins]]
config = "mixins.iris.fantastic.json"

[[mixins]]
config = "mixins.iris.vertexformat.json"

[[mixins]]
config = "iris-batched-entity-rendering.mixins.json"

[[mixins]]
config = "mixins.iris.compat.sodium.json"

[[mixins]]
config = "mixins.iris.compat.dh.json"

[[mixins]]
config = "mixins.iris.forge.json"

[mods."sodium:options"]
"mixin.features.render.world.sky" = false

[[dependencies.iris]]
modId = "embeddium"
type = "incompatible"
reason = "Iris and Embeddium cannot be used together. Please use Sodium 0.6+ instead."
versionRange = "[0.0.1,)"
ordering = "NONE"
side = "CLIENT"

[modproperties.iris]
"sodium:config_api_user" = "net.irisshaders.iris.compat.sodium.config.IrisConfig"